### ISSUE TITLE
No longer working on Heroku

### ISSUE THREAD

**Issue by max454545** [russellromney/dash-auth-flow#2]
I could be wrong, and it could just be my browser, but when I use your Heroku app, the user jumps from being logged in, to being logged out, and back to being logged in, all without clicking logout, and just by navigating.  What is happening?

**Comment by russellromney** [comment]
I had an error in the routing. I've fixed the error in 9b32495e752dac740ad0433fe3ca1fb7f4c38c9e

Note - you still won't be able to do anything that requires email interaction as it's not email-live.

**Comment by max454545** [comment]
Thanks @russellromney .  This looks like a good solution

**Comment by max454545** [comment]
I'm using this in deployment right now.  Can't thank you enough it works like a dream
