### ISSUE TITLE
two bugs and one issue

### ISSUE THREAD

**Issue by marketemp** [russellromney/dash-auth-flow#4]
bug 1, on line 123 of pages/profile.py the dashes need to be removed from -password on the list items, otherwise this creates a double-dash and an incorrect id

bug 2, I believe line 72 of pages/auth_pages/forgot_password.py needs to be removed.  It definitely causes an error when any email is entered that doesn't exist in the database.

the issue is that everything worked great in an environment that imported all the correctly versioned modules from requirements.txt.  However when I pulled the code into my environment that has a more recent Dash versions, prevent_initial_callbacks=True needs to be set within the app = dash.Dash( definition.  Otherwise all the callbacks load and error during the initial page load.

**Comment by russellromney** [comment]
Excellent issues raised! This repo needs to be updated with more recent versions of Dash and with a better flow.

**Comment by marketemp** [comment]
hi Russell,
funny the first correction I noticed was editing out "routing shit to".
great work on this!  this totally fills  critical missing gap in the free Dash product.  I really want to get into Dash Enterprise but it's priced so that only corporations can afford it.
Steve
    On Friday, October 16, 2020, 09:13:14 PM PDT, Russell Romney <notifications@github.com> wrote:  
 
 


Excellent issues raised! This repo needs to be updated with more recent versions of Dash and with a better flow.

**Comment by marketemp** [comment]
Just reviewed the changes and all look good.  Here are three more suggestions:
1.  If MAILJET_API_KEY is null there should be a message on how to get one and to put it in utilities/keys.py  There also should some way that the key gets displayed to the user to test everything out.  I had to add a print(key)
2. If a user logs in with a bad password, it would be nice if that were noted in the error message the same way that is done on the forgot password page.  A security expert may argue the opposite.
3. Add spaces after all commas!
    On Saturday, October 17, 2020, 12:13:14 AM EDT, Russell Romney <notifications@github.com> wrote:  
 
 


Excellent issues raised! This repo needs to be updated with more recent versions of Dash and with a better flow.

**Comment by marketemp** [comment]
#2.  meant incorrect email, not bad password
    On Saturday, October 17, 2020, 12:13:14 AM EDT, Russell Romney <notifications@github.com> wrote:  
 
 


Excellent issues raised! This repo needs to be updated with more recent versions of Dash and with a better flow.
